#!/bin/sh
set -e

# Exit with error if required environment is not present
if [ ! -f "/btmon.cfg" ]; then
  echo "Config doesn't exist"
  exit 1
fi

# Execute the btmon python script
./btmon.py -c /btmon.cfg
